name: Lint

on:
  push:
    branches:
      - main
  pull_request:

env:
  RUBY_VERSION: 3.2.2
  NODE_VERSION: 20.x

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - run: bundle exec rubocop -P
        name: Lint Ruby files

      - run: bundle exec erblint app/**/*.erb
        name: Lint ERB files

